@server1 = http://localhost:8484
@server2 = https://support-manager-api.vercel.app
@gralToken = Bearer estacionartManager@2024
@gralToken2 = Bearer bAcK


###
# PING
GET {{server1}}/ping
content-type: application/json

##
###
# Get profiles
GET {{server1}}/back/v1/params/profiles
Authorization: {{gralToken}}
content-type: application/json

##
###
# Get Project's status
GET {{server1}}/back/v1/params/project_status
Authorization: {{gralToken}}
content-type: application/json
