@server1 = http://localhost:8484
@server2 = https://support-manager-api.vercel.app
@gralToken = Bearer estacionartManager@2024
@gralToken2 = Bearer bAcK


###
# PING
GET {{server1}}/ping
content-type: application/json


##
###
# Get all project's
GET {{server1}}/back/v1/projects
Authorization: {{gralToken}}
content-type: application/json



##
###
# Get specific project
GET {{server1}}/back/v1/projects/1
Authorization: {{gralToken}}
content-type: application/json


##
###
# Update shop status
PUT {{server1}}/back/v1/projects/status
Authorization: {{gralToken}}
content-type: application/json

{
    "project_id": 1,
    "status": true
}




# ##
# ###
# # Get project's users list
# GET {{server1}}/back/v1/projects/99/users
# Authorization: {{gralToken}}
# content-type: application/json



# ##
# ###
# # Get shop's users list
# GET {{server1}}/back/v1/shops/99/users
# Authorization: {{gralToken}}
# content-type: application/json


##
###
# Create project
POST {{server1}}/back/v1/projects
Authorization: {{gralToken}}
content-type: application/json

{
  "name": "MAVER",
  "description": "La digital",
  "responsable": "Jose A.",
  "logo": "https://as...",
  "platforms": [
    "WEB",
    "BACKOFFICE"
  ],
  "enabled": true
}


##
###
# Update project
PUT {{server1}}/back/v1/projects
Authorization: {{gralToken}}
content-type: application/json

{
  "id": 4,
  "name": "MAVER",
  "description": "La digital",
  "responsable": "Jose A.",
  "logo": "https://as...",
  "platforms": [
    "WEB",
    "BACKOFFICE"
  ],
  "enabled": false
 
}