@server1 = http://localhost:8484
@server2 = https://support-manager-api.vercel.app

@gralToken = Bearer estacionartManager@2024
@gralToken2 = Bearer bAcK

###
# PING
GET {{server1}}/ping
content-type: application/json


###
# GET Tickets list
GET {{server1}}/back/v1/tickets
Authorization: {{gralToken2}}
content-type: application/json



###
# GET Ticket by ID
GET {{server1}}/back/v1/tickets/2
Authorization: {{gralToken}}
content-type: application/json

##
###
# Create ticket
POST {{server1}}/back/v1/tickets
Authorization: {{gralToken}}
content-type: application/json

{
  "project_id": 1,
  "type": "BUG", 
  "platform": "WEB",
  "location": "Sistemas/Usuarios",
  "current_result": "No puedo crear un usuario",
  "expected_result": "",
  "suggestion": "Deberia ser mas sencillo poder. ...",
  "screenshot": "httsp:...",
  "creator_id": "V6bXRKpxoZUkvRB0BHmESufq1tC3"
}



##
###
# Add message to specific ticket
POST {{server1}}/back/v1/tickets/messages
Authorization: {{gralToken}}
content-type: application/json

{
  "ticket_id": 15,
  "message": "Necesito una respuesta al error..."
}



##
###
# Update ticket
PUT {{server1}}/back/v1/tickets
Authorization: {{gralToken}}
content-type: application/json

{
  "id": 2,
  "project_id": 1,
  "type": "BUG", 
  "platform": "WEB",
  "location": "Sistemas/Usuarios",
  "current_result": "No puedo crear un usuario",
  "expected_result": "",
  "suggestion": "Deberia ser mas sencillo poder. ...",
  "screenshot": "httsp:...",
  "creator_id": "nQepALQnjvfQyqWvBHUISOiZkb02"
}


##
###
# Update ticket status
PUT {{server1}}/back/v1/tickets/status
Authorization: {{gralToken}}
content-type: application/json

{
  "id": 2,
  "status_id": 5
}





